### ISSUE TITLE
Failed to parse an unconventional regex

### ISSUE THREAD

**Issue by Zamralik** [stryker-mutator/weapon-regex#298]
Hello!

For fun, I wanted to use the native node:test & node:assert.
Sadly, it doesn't have a feature to mock imported modules when doing tests.
So as a side project, I wanted to see if I could make a custom loader that would allow just that.

When trying to run stryker, weapon-regex was stumped on my import regex and could not parse it.

```js
/import\s*(?<imported_items>.+?)\s*from\s*['"](?<dependency_identifier>[^'"]+)['"]/g
```
It could be that he is stumped by the named capturing groups `<imported_items>` and `<dependency_identifier>`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Named_capturing_group

The error message was

```
[RegexMutator]: The Regex parser of weapon-regex couldn't parse this regex pattern:
"import\s*(?<imported_items>.+?)\s*from\s*['"](?<dependency_identifier>[^'"]+)['"]".
Please report this issue at https://github.com/stryker-mutator/weapon-regex/issues.
Inner error: [Error] Parser: Position 1:10, found "(?<importe"
```

**Comment by nhaajt** [comment]
This happened because JVM and JS have different definitions of a valid group name.

In JVM, a group name is simply `[A-Za-z][A-Za-z0-9]` ([source](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html#groupname)), which weapon-regex is currently using.

In JS, it is a bit more complicated. It only says that a group name must be a valid identifier ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Named_capturing_group#name)), but it doesn’t say whether all identifiers are valid group name. 
> In JavaScript, identifiers are commonly made of alphanumeric characters, underscores (`_`), and dollar signs (`$`). Identifiers are not allowed to start with numbers. However, JavaScript identifiers are not only limited to ASCII — many Unicode code points are allowed as well.
>
> ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#identifiers))

Some quick tests on [regex101](https://regex101.com/r/OAekVc) show that JS doesn't allow group names with `$` or Unicode characters.

I added support for JS group names with underscores in #300.
